# Generated by Django 4.2.5 on 2023-10-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Este campo deve estar marcado para que a página seja exibida publicamente.'),
        ),
    ]
