# Generated by Django 4.2.6 on 2023-10-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
    ]
